name: test

on: [push]

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@master

        - uses: leafo/gh-actions-lua@v8.0.0
          with:
            luaVersion: "5.1"

        - uses: leafo/gh-actions-luarocks@v4.0.0

        - name: build 
          run: |
            luarocks make inifile-dev-1.rockspec
            luarocks install busted

        - name: test
          run: |
            busted -o utfTerminal .
